version: 2

sources:

    - name: jaffle_shop
      description: This is a replica of the Snowflake database used for our app
      database: raw
      schema: jaffle_shop
      tables:
          - name: customers
            description: Raw customers data
            columns:
              - name: id
                description: Primary key for the raw customers data
                tests:
                  - unique
                  - not_null
          - name: orders
            description: Raw orders data
            columns:
              - name: id
                description: Primary key for the raw orders data
                tests:
                  - unique
                  - not_null
            loaded_at_field: _etl_loaded_at
            freshness:
              warn_after: {count: 24, period: hour}
    
    - name: stripe
      description: This is a replica of the Snowflake database used for our app
      database: raw
      schema: stripe
      tables:
          - name: payment
            description: One record per payment event.
            loaded_at_field: _batched_at
            freshness:
              warn_after: {count: 24, period: hour}